# Generated by Django 5.2.3 on 2025-07-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_paid_order_strip_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='strip_token',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
