# Generated by Django 5.2.3 on 2025-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('meal', 'Meal'), ('femeal', 'Femeal')], default='meal'),
        ),
    ]
